let i = 0

setTimeout(() => alert(i), 100);

for (let i = 0; i < 10; i++) {
  i++;
}

/*
LA FUNCION SE EJECUTA DESPUES DE EL BUCLE, YA QUE ES UNA FUNCION ASINCRONA Y TIENE UN TIEMPO DE ESPERA, ASI EL TIEMPO DE ESPERA SEA POCO
LO QUE PASA ES QUE SE EJECUTARA EL FOR Y DESPUES LA FUNCIÓN, Y EL ALERT VA A MOSTAR EL 0
*/